import React from 'react'
import BuyTransactionDetails from './buyTransactionDetails/buyTransactionDetails'

function BuyHistory() {


  // dummy Data For Example
  const buyHistoryDetails = [{
    sno: 1,
    transactionId: "279RWYX",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:25 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:25 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  {
    sno: 2,
    transactionId: "041VDZS",
    amount: "₹0.00",
    type: "Credit",
    paymentMethod: "Available Balance",
    currency: "INR",
    transactionDate: "29-04-2025 5:24 PM",
    status: "Completed",
    reason: "N/A",
    updatedBy: "N/A",
    updatedOn: "29-04-2025 5:24 PM",
  },
  ];

  return (
    <div >
      <BuyTransactionDetails data={buyHistoryDetails} />
    </div>
  )
}

export default BuyHistory
